/**
 * POST /api/admin/create-fellowship
 *
 * Body: { name: string, leader_email: string }
 * Looks up the user by email (auth admin API), inserts a fellowship row,
 * and returns the auto-generated invite_code from the DB trigger.
 *
 * 仅 super_admin 可调用。
 */

import { NextRequest, NextResponse } from 'next/server'
import { createClient, createServiceClient } from '@/lib/supabase/server'
import { z } from 'zod'

export const runtime = 'nodejs'

const BodySchema = z.object({
  name:         z.string().min(1).max(100),
  leader_email: z.string().email(),
})

async function getAdminUser() {
  const supabase = createClient()
  const { data: { user }, error } = await supabase.auth.getUser()
  if (error || !user) return null
  const db = createServiceClient()
  const { data: profile } = await db
    .from('users').select('role').eq('id', user.id).single()
  return profile?.role === 'super_admin' ? user : null
}

export async function POST(req: NextRequest) {
  const admin = await getAdminUser()
  if (!admin) return NextResponse.json({ error: 'forbidden' }, { status: 403 })

  const body = await req.json().catch(() => ({}))
  const parsed = BodySchema.safeParse(body)
  if (!parsed.success) {
    return NextResponse.json({ error: 'invalid_params' }, { status: 400 })
  }

  const { name, leader_email } = parsed.data
  const db = createServiceClient()

  // ── 1. Resolve leader_email → user id via auth admin API ─────────────
  // listUsers fetches up to 1000 users; fine for small congregation apps.
  const { data: authData, error: listErr } = await db.auth.admin.listUsers({
    page: 1, perPage: 1000,
  })
  if (listErr) {
    console.error('[create-fellowship] auth list error:', listErr.message)
    return NextResponse.json({ error: 'auth_error' }, { status: 500 })
  }

  const leader = authData.users.find(u => u.email === leader_email)
  if (!leader) {
    return NextResponse.json({ error: 'leader_not_found' }, { status: 404 })
  }

  // ── 2. Verify the found user has at least 'leader' role ──────────────
  const { data: leaderProfile } = await db
    .from('users').select('role, display_name').eq('id', leader.id).single()

  if (!leaderProfile || leaderProfile.role === 'member') {
    return NextResponse.json(
      { error: 'leader_role_required', message: '该用户角色不足，请先将其提升为组长' },
      { status: 422 }
    )
  }

  // ── 3. Insert fellowship — invite_code generated by DB trigger ────────
  const { data: fellowship, error: insertErr } = await db
    .from('fellowships')
    .insert({ name, leader_id: leader.id, status: 'approved' })
    .select('id, invite_code, name')
    .single()

  if (insertErr || !fellowship) {
    console.error('[create-fellowship] insert error:', insertErr?.code)
    return NextResponse.json({ error: 'db_error' }, { status: 500 })
  }

  return NextResponse.json({
    fellowship_id: fellowship.id,
    name:          fellowship.name,
    invite_code:   fellowship.invite_code,
    leader_name:   leaderProfile.display_name,
  })
}
